#!/bin/bash
SERVER_PROPERTIES=server.properties
MINECRAFT_SERVER_JAR=minecraft.jar

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$MINECRAFT_SERVER_JAR" ]; then
	wget "https://github.com/el-kazakh/minecraft/raw/master/minecraft.jar" -O $MINECRAFT_SERVER_JAR
fi

